import type { Nav } from "@/types";

export const NavList: Nav[] = [
  {
    id: "1",
    name: "主页",
    icon: "i-akar-icons:home",
    children: [
      {
        id: "h-1",
        name: "GitHub",
        logo: "i-simple-icons:github",
        url: "https://github.com",
        background: "#24292e",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-2",
        name: "Google",
        logo: "i-simple-icons:google",
        url: "https://google.com",
        background: "#4285f4",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-3",
        name: "YouTube",
        logo: "i-simple-icons:youtube",
        url: "https://youtube.com",
        background: "#ff0000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-4",
        name: "Twitter",
        logo: "i-simple-icons:x",
        url: "https://x.com",
        background: "#000000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-5",
        name: "Bilibili",
        logo: "i-simple-icons:bilibili",
        url: "https://bilibili.com",
        background: "#00aeec",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-6",
        name: "知乎",
        logo: "i-simple-icons:zhihu",
        url: "https://zhihu.com",
        background: "#0084ff",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-7",
        name: "Notion",
        logo: "i-simple-icons:notion",
        url: "https://notion.so",
        background: "#000000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "h-8",
        name: "Reddit",
        logo: "i-simple-icons:reddit",
        url: "https://reddit.com",
        background: "#ff4500",
        type: "icon",
        size: "1x1",
      },
    ],
  },
  {
    id: "2",
    name: "编程",
    icon: "i-gravity-ui:code",
    children: [
      {
        id: "p-1",
        name: "VS Code",
        logo: "i-simple-icons:visualstudiocode",
        url: "https://vscode.dev",
        background: "#007acc",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-2",
        name: "GitHub",
        logo: "i-simple-icons:github",
        url: "https://github.com",
        background: "#24292e",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-3",
        name: "Stack Overflow",
        logo: "i-simple-icons:stackoverflow",
        url: "https://stackoverflow.com",
        background: "#f48024",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-4",
        name: "npm",
        logo: "i-simple-icons:npm",
        url: "https://npmjs.com",
        background: "#cb3837",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-5",
        name: "Docker",
        logo: "i-simple-icons:docker",
        url: "https://hub.docker.com",
        background: "#2496ed",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-6",
        name: "Vercel",
        logo: "i-simple-icons:vercel",
        url: "https://vercel.com",
        background: "#000000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-7",
        name: "MDN",
        logo: "i-simple-icons:mdnwebdocs",
        url: "https://developer.mozilla.org",
        background: "#1f6feb",
        type: "icon",
        size: "1x1",
      },
      {
        id: "p-8",
        name: "Netlify",
        logo: "i-simple-icons:netlify",
        url: "https://netlify.com",
        background: "#00c7b7",
        type: "icon",
        size: "1x1",
      },
    ],
  },
  {
    id: "3",
    name: "设计",
    icon: "i-ic:outline-draw",
    children: [
      {
        id: "d-1",
        name: "Figma",
        logo: "i-simple-icons:figma",
        url: "https://figma.com",
        background: "#f24e1e",
        type: "icon",
        size: "1x1",
      },
      {
        id: "d-2",
        name: "Dribbble",
        logo: "i-simple-icons:dribbble",
        url: "https://dribbble.com",
        background: "#ea4c89",
        type: "icon",
        size: "1x1",
      },
      {
        id: "d-3",
        name: "Behance",
        logo: "i-simple-icons:behance",
        url: "https://behance.net",
        background: "#0057ff",
        type: "icon",
        size: "1x1",
      },
      {
        id: "d-4",
        name: "Unsplash",
        logo: "i-simple-icons:unsplash",
        url: "https://unsplash.com",
        background: "#000000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "d-5",
        name: "Canva",
        logo: "i-simple-icons:canva",
        url: "https://canva.com",
        background: "#00c4cc",
        type: "icon",
        size: "1x1",
      },
      {
        id: "d-6",
        name: "Adobe XD",
        logo: "i-simple-icons:adobexd",
        url: "https://adobe.com/products/xd.html",
        background: "#ff61f6",
        type: "icon",
        size: "1x1",
      },
    ],
  },
  {
    id: "4",
    name: "产品",
    icon: "i-lucide:circle-parking",
    children: [
      {
        id: "pm-1",
        name: "Notion",
        logo: "i-simple-icons:notion",
        url: "https://notion.so",
        background: "#000000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "pm-2",
        name: "Jira",
        logo: "i-simple-icons:jira",
        url: "https://atlassian.com/software/jira",
        background: "#0052cc",
        type: "icon",
        size: "1x1",
      },
      {
        id: "pm-3",
        name: "Trello",
        logo: "i-simple-icons:trello",
        url: "https://trello.com",
        background: "#0052cc",
        type: "icon",
        size: "1x1",
      },
      {
        id: "pm-4",
        name: "Miro",
        logo: "i-simple-icons:miro",
        url: "https://miro.com",
        background: "#ffd02f",
        type: "icon",
        size: "1x1",
      },
      {
        id: "pm-5",
        name: "Linear",
        logo: "i-simple-icons:linear",
        url: "https://linear.app",
        background: "#5e6ad2",
        type: "icon",
        size: "1x1",
      },
      {
        id: "pm-6",
        name: "Confluence",
        logo: "i-simple-icons:confluence",
        url: "https://atlassian.com/software/confluence",
        background: "#0052cc",
        type: "icon",
        size: "1x1",
      },
    ],
  },
  {
    id: "5",
    name: "AI",
    icon: "i-icon-park-outline:magic-wand",
    children: [
      {
        id: "ai-1",
        name: "ChatGPT",
        logo: "i-simple-icons:openai",
        url: "https://chat.openai.com",
        background: "#10a37f",
        type: "icon",
        size: "1x1",
      },
      {
        id: "ai-2",
        name: "Claude",
        logo: "i-simple-icons:anthropic",
        url: "https://claude.ai",
        background: "#d97706",
        type: "icon",
        size: "1x1",
      },
      {
        id: "ai-3",
        name: "Gemini",
        logo: "i-simple-icons:googlegemini",
        url: "https://gemini.google.com",
        background: "#4285f4",
        type: "icon",
        size: "1x1",
      },
      {
        id: "ai-4",
        name: "Perplexity",
        logo: "i-simple-icons:perplexity",
        url: "https://perplexity.ai",
        background: "#20b2aa",
        type: "icon",
        size: "1x1",
      },
      {
        id: "ai-5",
        name: "Hugging Face",
        logo: "i-simple-icons:huggingface",
        url: "https://huggingface.co",
        background: "#ff9d00",
        type: "icon",
        size: "1x1",
      },
      {
        id: "ai-6",
        name: "Midjourney",
        logo: "i-simple-icons:midjourney",
        url: "https://midjourney.com",
        background: "#000000",
        type: "icon",
        size: "1x1",
      },
    ],
  },
  {
    id: "6",
    name: "摸鱼",
    icon: "i-meteor-icons:gamepad-modern",
    children: [
      {
        id: "f-1",
        name: "Netflix",
        logo: "i-simple-icons:netflix",
        url: "https://netflix.com",
        background: "#e50914",
        type: "icon",
        size: "1x1",
      },
      {
        id: "f-2",
        name: "Spotify",
        logo: "i-simple-icons:spotify",
        url: "https://spotify.com",
        background: "#1db954",
        type: "icon",
        size: "1x1",
      },
      {
        id: "f-3",
        name: "Steam",
        logo: "i-simple-icons:steam",
        url: "https://store.steampowered.com",
        background: "#1b2838",
        type: "icon",
        size: "1x1",
      },
      {
        id: "f-4",
        name: "Bilibili",
        logo: "i-simple-icons:bilibili",
        url: "https://bilibili.com",
        background: "#00aeec",
        type: "icon",
        size: "1x1",
      },
      {
        id: "f-5",
        name: "YouTube",
        logo: "i-simple-icons:youtube",
        url: "https://youtube.com",
        background: "#ff0000",
        type: "icon",
        size: "1x1",
      },
      {
        id: "f-6",
        name: "Reddit",
        logo: "i-simple-icons:reddit",
        url: "https://reddit.com",
        background: "#ff4500",
        type: "icon",
        size: "1x1",
      },
    ],
  },
];
